[project]
name = "automata-5-git"
version = "0.1.0"
description = "Dynamic Programming exercise from Automata, Algorithms & Complexity class - Fall 2025"
requires-python = ">=3.14"
dependencies = [
    "tabulate>=0.9.0",
]
